server:
  port: 81

twitter-listener-service:
  tweet-keywords:
    - Forex
    - EURUSD
    - DXY
    - FX
    - EURUSD
    - economy
    - news
    - latestnews
    - euronews
    - breaking news
