server:
  port: 80

twitter-listener-service:
  tweet-keywords:
    - '#Diablo 2 Resurrected'
    - '#Diablo 2'
    - '#D2R'
    - '#LateLateShow'
    - '#Bob Geldof'
    - '#Athlone'
    - '#Ireland'
    - '#BobGeldof'
    - '#LateLate'
    - '#US'
    - '#America'
    - '#Bitcoin'
    - '#Crypto'
    - '#Forex'
    - '#Trump'
    - '#USA'







